USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ETL_PROJECT_DB;

USE DATABASE ETL_PROJECT_DB;

CREATE WAREHOUSE IF NOT EXISTS ETL_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

USE WAREHOUSE ETL_WH;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MART;


-- =========================================================
-- S3 STORAGE INTEGRATION
-- =========================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_ROLE_NAME>'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://<S3_BUCKET_NAME>/'
    );


-- =========================================================
-- GRANTS
-- =========================================================

GRANT USAGE ON INTEGRATION S3_INTEGRATION TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE ETL_PROJECT_DB TO ROLE SYSADMIN;

GRANT USAGE ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;
GRANT CREATE FILE FORMAT ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;
GRANT CREATE STAGE ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;
GRANT CREATE STREAM ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;
GRANT CREATE PIPE ON SCHEMA ETL_PROJECT_DB.RAW TO ROLE SYSADMIN;

GRANT USAGE ON SCHEMA ETL_PROJECT_DB.STAGING TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA ETL_PROJECT_DB.STAGING TO ROLE SYSADMIN;
GRANT CREATE PROCEDURE ON SCHEMA ETL_PROJECT_DB.STAGING TO ROLE SYSADMIN;
GRANT CREATE TASK ON SCHEMA ETL_PROJECT_DB.STAGING TO ROLE SYSADMIN;

GRANT USAGE ON SCHEMA ETL_PROJECT_DB.MART TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA ETL_PROJECT_DB.MART TO ROLE SYSADMIN;


-- =========================================================
-- RETURN TO SYSADMIN
-- =========================================================

USE ROLE SYSADMIN;

USE DATABASE ETL_PROJECT_DB;

USE WAREHOUSE ETL_WH;


-- =========================================================
-- FILE FORMAT
-- =========================================================

CREATE OR REPLACE FILE FORMAT ETL_PROJECT_DB.RAW.CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    NULL_IF = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;


-- =========================================================
-- S3 STAGE
-- =========================================================

CREATE OR REPLACE STAGE ETL_PROJECT_DB.RAW.S3_STAGE
    STORAGE_INTEGRATION = S3_INTEGRATION
    URL = 's3://<S3_BUCKET_NAME>/'
    FILE_FORMAT = ETL_PROJECT_DB.RAW.CSV_FORMAT;


-- =========================================================
-- RAW TABLE
-- =========================================================

CREATE OR REPLACE TABLE ETL_PROJECT_DB.RAW.RAW_CUSTOMERS
(
    CUSTOMER_KEY INTEGER,
    PREFIX VARCHAR(10),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    BIRTH_DATE VARCHAR(20),
    MARITAL_STATUS VARCHAR(5),
    GENDER VARCHAR(5),
    EMAIL_ADDRESS VARCHAR(200),
    ANNUAL_INCOME VARCHAR(50),
    TOTAL_CHILDREN INTEGER,
    EDUCATION_LEVEL VARCHAR(50),
    OCCUPATION VARCHAR(50),
    HOME_OWNER VARCHAR(5),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- =========================================================
-- RAW STREAM
-- =========================================================

CREATE OR REPLACE STREAM ETL_PROJECT_DB.RAW.RAW_CUSTOMERS_STREAM
    ON TABLE ETL_PROJECT_DB.RAW.RAW_CUSTOMERS
    APPEND_ONLY = TRUE;


-- =========================================================
-- SNOWPIPE
-- =========================================================

CREATE OR REPLACE PIPE ETL_PROJECT_DB.RAW.CUSTOMERS_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO ETL_PROJECT_DB.RAW.RAW_CUSTOMERS
(
    CUSTOMER_KEY,
    PREFIX,
    FIRST_NAME,
    LAST_NAME,
    BIRTH_DATE,
    MARITAL_STATUS,
    GENDER,
    EMAIL_ADDRESS,
    ANNUAL_INCOME,
    TOTAL_CHILDREN,
    EDUCATION_LEVEL,
    OCCUPATION,
    HOME_OWNER
)
FROM @ETL_PROJECT_DB.RAW.S3_STAGE
FILE_FORMAT = (
    FORMAT_NAME = ETL_PROJECT_DB.RAW.CSV_FORMAT
)
ON_ERROR = 'CONTINUE';


-- =========================================================
-- STAGING TABLE
-- =========================================================

CREATE OR REPLACE TABLE ETL_PROJECT_DB.STAGING.STG_CUSTOMER
(
    CUSTOMER_KEY INTEGER,
    PREFIX VARCHAR(10),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    BIRTH_DATE VARCHAR(20),
    MARITAL_STATUS VARCHAR(5),
    GENDER VARCHAR(5),
    EMAIL_ADDRESS VARCHAR(200),
    ANNUAL_INCOME NUMBER(12,2),
    TOTAL_CHILDREN INTEGER,
    EDUCATION_LEVEL VARCHAR(50),
    OCCUPATION VARCHAR(50),
    HOME_OWNER VARCHAR(5),
    _STAGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- =========================================================
-- MART TABLE
-- =========================================================

CREATE OR REPLACE TABLE ETL_PROJECT_DB.MART.DIM_CUSTOMERS
(
    CUSTOMER_KEY INTEGER,
    PREFIX VARCHAR(10),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    BIRTH_DATE VARCHAR(20),
    MARITAL_STATUS VARCHAR(5),
    GENDER VARCHAR(5),
    GENDER_DESC VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(200),
    ANNUAL_INCOME NUMBER(12,2),
    TOTAL_CHILDREN INTEGER,
    EDUCATION_LEVEL VARCHAR(50),
    OCCUPATION VARCHAR(50),
    HOME_OWNER VARCHAR(5),
    CUSTOMER_SEGMENT VARCHAR(30),
    _MART_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

