USE ROLE SYSADMIN;
USE DATABASE ETL_PROJECT_DB;
USE WAREHOUSE ETL_WH;

SHOW INTEGRATIONS LIKE 'S3_INTEGRATION';

DESC INTEGRATION S3_INTEGRATION;

SHOW FILE FORMATS IN SCHEMA ETL_PROJECT_DB.RAW;

DESC STAGE ETL_PROJECT_DB.RAW.S3_STAGE;

LIST @ETL_PROJECT_DB.RAW.S3_STAGE;

DESC TABLE ETL_PROJECT_DB.RAW.RAW_CUSTOMERS;

SHOW STREAMS IN SCHEMA ETL_PROJECT_DB.RAW;

SHOW PIPES LIKE 'CUSTOMERS_PIPE'
IN SCHEMA ETL_PROJECT_DB.RAW;

SELECT SYSTEM$PIPE_STATUS(
    'ETL_PROJECT_DB.RAW.CUSTOMERS_PIPE'
);

SHOW TASKS LIKE 'PROCESS_CUSTOMERS_TASK'
IN SCHEMA ETL_PROJECT_DB.STAGING;

SHOW PIPES LIKE 'CUSTOMERS_PIPE'
IN SCHEMA ETL_PROJECT_DB.RAW;

ALTER PIPE ETL_PROJECT_DB.RAW.CUSTOMERS_PIPE
REFRESH;

SELECT SYSTEM$PIPE_STATUS(
    'ETL_PROJECT_DB.RAW.CUSTOMERS_PIPE'
);

SELECT
    COUNT(*) AS RAW_COUNT
FROM ETL_PROJECT_DB.RAW.RAW_CUSTOMERS;

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    ANNUAL_INCOME
FROM ETL_PROJECT_DB.RAW.RAW_CUSTOMERS
LIMIT 10;

SELECT
    COUNT(*) AS STAGING_COUNT
FROM ETL_PROJECT_DB.STAGING.STG_CUSTOMER;

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    ANNUAL_INCOME
FROM ETL_PROJECT_DB.STAGING.STG_CUSTOMER
LIMIT 10;

SELECT
    COUNT(*) AS MART_COUNT
FROM ETL_PROJECT_DB.MART.DIM_CUSTOMERS;

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    ANNUAL_INCOME,
    GENDER_DESC,
    CUSTOMER_SEGMENT
FROM ETL_PROJECT_DB.MART.DIM_CUSTOMERS
LIMIT 10;

SELECT *
FROM TABLE
(
    INFORMATION_SCHEMA.COPY_HISTORY
    (
        TABLE_NAME => 'ETL_PROJECT_DB.RAW.RAW_CUSTOMERS',
        START_TIME => DATEADD(
            'hour',
            -6,
            CURRENT_TIMESTAMP()
        )
    )
)
ORDER BY LAST_LOAD_TIME DESC;

SELECT *
FROM TABLE
(
    INFORMATION_SCHEMA.TASK_HISTORY
    (
        TASK_NAME => 'ETL_PROJECT_DB.STAGING.PROCESS_CUSTOMERS_TASK',
        SCHEDULED_TIME_RANGE_START => DATEADD(
            'hour',
            -6,
            CURRENT_TIMESTAMP()
        )
    )
)
ORDER BY SCHEDULED_TIME DESC;

SELECT *
FROM ETL_PROJECT_DB.RAW.RAW_CUSTOMERS_STREAM
LIMIT 20;

DESC INTEGRATION S3_INTEGRATION;

DESC STAGE ETL_PROJECT_DB.RAW.S3_STAGE;

DESC PIPE ETL_PROJECT_DB.RAW.CUSTOMERS_PIPE;

SELECT
    'RAW' AS LAYER,
    COUNT(*) AS RECORD_COUNT
FROM ETL_PROJECT_DB.RAW.RAW_CUSTOMERS

UNION ALL

SELECT
    'STAGING' AS LAYER,
    COUNT(*) AS RECORD_COUNT
FROM ETL_PROJECT_DB.STAGING.STG_CUSTOMER

UNION ALL

SELECT
    'MART' AS LAYER,
    COUNT(*) AS RECORD_COUNT
FROM ETL_PROJECT_DB.MART.DIM_CUSTOMERS;

CALL ETL_PROJECT_DB.STAGING.PROCESS_CUSTOMERS();